//! LDPC(174,87) belief-propagation decode for JS8Call.
//!
//! A faithful Rust port of `bpdecode174()` in `js8call/JS8.cpp`, over the
//! same parity structure (`Mn` / `Nm`) that code uses. The (174, 87)
//! low-density parity-check code was generated by the PEG algorithm from
//! a 87x87 parity matrix (see `frame.rs::encode` for the corresponding
//! systematic encoder). Decoding is the standard min-sum / tanh
//! (soft-output) belief-propagation iteration over the Tanner graph:
//!
//! - `MN`: variable->check messages (each of the 174 bits checks 3 parity
//!   checks);
//! - `NM`: check->variable messages (each of the 87 parity checks covers
//!   6 or 7 bits).
//!
//! On success the last 87 bits of the decoded 174-bit codeword are the
//! message (JS8 transmits parity first, message last).

use super::ldpc_tables::{MN, NM};
use super::params::{BP_MAX_CHECKS, BP_MAX_ITERATIONS, K, M, N};

/// Belief-propagation decode a 174-bit LDPC codeword from float LLRs.
///
/// Writes the 87-bit message into `decoded` (as 0/1) and the hard
/// codeword (174 0/1 bits) into `cw`. Returns the number of hard errors
/// (bits where the hard decision disagrees with the LLR sign), or `-1`
/// if no valid codeword was found or the early-stopping criterion fired.
///
/// Port of `bpdecode174`:
///
/// ```ignore
/// int bpdecode174(const float *llr, int *decoded, int *cw)
/// ```
pub fn bpdecode174(llr: &[f32; N], decoded: &mut [i8; K], cw: &mut [i8; N]) -> i32 {
    const BP_MAX_ROWS: usize = 7;

    // Messages to variable nodes, from check nodes (3 per bit).
    let mut tov: [[f32; BP_MAX_CHECKS]; N] = [[0.0; BP_MAX_CHECKS]; N];
    // Messages to check nodes, from variable nodes (variable width per check).
    let mut toc: [[f32; BP_MAX_ROWS]; M] = [[0.0; BP_MAX_ROWS]; M];
    // tanh of the bit->check messages, per check node.
    let mut tanhtoc: [[f32; BP_MAX_ROWS]; M] = [[0.0; BP_MAX_ROWS]; M];

    // Bit log-likelihood ratios combined with check-node contributions.
    let mut zn = [0.0f32; N];
    // Syndrome of the current hard codeword, per check node.
    let mut synd = [0i32; M];

    let mut ncnt: i32 = 0;
    let mut nclast: i32 = 0;

    // Initialize toc (messages from bits to checks).
    for i in 0..M {
        for j in 0..NM[i].valid {
            toc[i][j] = llr[NM[i].bits[j] as usize];
        }
    }

    // Iterative decoding.
    for iter in 0..=BP_MAX_ITERATIONS {
        // Update bit log-likelihood ratios.
        for i in 0..N {
            let mut acc = llr[i];
            for k in 0..BP_MAX_CHECKS {
                acc += tov[i][k];
            }
            zn[i] = acc;
        }

        // Hard decision, syndrome.
        for i in 0..N {
            cw[i] = if zn[i] > 0.0 { 1 } else { 0 };
        }

        let mut ncheck: i32 = 0;
        for i in 0..M {
            let mut s: i32 = 0;
            for j in 0..NM[i].valid {
                s += cw[NM[i].bits[j] as usize] as i32;
            }
            synd[i] = s;
            if s % 2 != 0 {
                ncheck += 1;
            }
        }

        if ncheck == 0 {
            // Valid codeword: extract the last N-M bits (the message).
            decoded.copy_from_slice(&cw[M..]);

            // Count hard errors: bits whose hard decision and LLR sign
            // disagree.
            let mut nerr: i32 = 0;
            for i in 0..N {
                if (2 * cw[i] - 1) as f32 * llr[i] < 0.0 {
                    nerr += 1;
                }
            }
            return nerr;
        }

        // Early-stopping criterion.
        if iter > 0 {
            let nd = ncheck - nclast;
            if nd < 0 {
                ncnt = 0;
            } else {
                ncnt += 1;
            }
            if ncnt >= 5 && iter >= 10 && ncheck > 15 {
                return -1;
            }
        }
        nclast = ncheck;

        // Bit -> check messages.
        for i in 0..M {
            for j in 0..NM[i].valid {
                let ibj = NM[i].bits[j] as usize;
                let mut v = zn[ibj];
                for k in 0..BP_MAX_CHECKS {
                    if MN[ibj][k] as i32 == i as i32 {
                        v -= tov[ibj][k];
                    }
                }
                toc[i][j] = v;
            }
        }

        // Check -> variable messages.
        for i in 0..M {
            for j in 0..BP_MAX_ROWS {
                tanhtoc[i][j] = (-toc[i][j] / 2.0).tanh();
            }
        }

        for i in 0..N {
            for j in 0..BP_MAX_CHECKS {
                let ichk = MN[i][j] as usize;
                let mut t = 1.0f32;
                for k in 0..NM[ichk].valid {
                    if NM[ichk].bits[k] as usize != i {
                        t *= tanhtoc[ichk][k];
                    }
                }
                tov[i][j] = 2.0 * (-t).atanh();
            }
        }
    }

    -1
}
